name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install vulnerability package
        run: pnpm add openssl lodash@4.17.17 vite@5.0.4 google-translate-api-browser@4.1.2

      - name: Install dependencies
        run: pnpm install

      - name: Test Local Action - Low
        id: test-action-low
        uses: ./
        with:
          level: low
          fails: false

      - name: Test Local Action - Moderate
        id: test-action-medium
        uses: ./
        with:
          level: moderate
          fails: false

      - name: Test Local Action - High
        id: test-action-high
        uses: ./
        with:
          level: high
          fails: false

      - name: Test Local Action - Critical
        id: test-action-critical
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: critical
          fails: false
