name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install vulnerability package
        run: pnpm add lodash@4.17.17

      - name: Test Local Action - Low
        id: test-action-low
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: low
          fails: false

      - name: Install vulnerability package
        run: pnpm add openssl

      - name: Test Local Action - Critical
        id: test-action-critical
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: critical
          fails: false
